### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by ghost** [hereafter/ssh-vault-vscode#1]
How are the credentials stored on disk?

**Comment by ghost** [comment]
@hereafter

**Comment by hereafter** [comment]
Right now the storage and access management is done by Windows (Windows Credential APIs)
https://docs.microsoft.com/en-us/windows/win32/secauthn/credentials-management


Once you are signed in, all applications with the access right to windows credential will have api access to them.

![image](https://user-images.githubusercontent.com/1483954/163804158-d441a1a5-1c52-4a49-b600-b134c19bc716.png)

The application right now does not store any information outside windows system.


Same as your git credentials, network sharing credentials etc.

Update me if the above information helps.

**Comment by ghost** [comment]
All applications? That seems a bit much. Thanks for explaining!

**Comment by hereafter** [comment]
yup the design principles are apps with access rights are users. you decided to run them
